version: '3'

services:
  data-service:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  processing-service:
    build:
      context: .
      dockerfile: Dockerfile.key_processing
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  logging-service:
    build:
      context: .
      dockerfile: Dockerfile.logging
    ports:
      - "5002:5002"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
