# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app


# Install any needed packages 
RUN pip install Flask pymongo bcrypt PyJWT

# Make port 5000 
EXPOSE 5000

# Define environment variable for MongoDB connection string
ENV MONGO_URI mongodb://localhost:27017

# Run data_controller.py when the container launches
CMD ["python3", "data_controller.py"]