# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install Flask pymongo PyJWT

# Make port 5001 available 
EXPOSE 5001

# Define environment variable for MongoDB connection string
ENV MONGO_URI mongodb://localhost:27017

# Run api_key_generator_service.py when the container launches
CMD ["python3", "api_key_generator_service.py"]