# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install Flask pymongo

EXPOSE 5002

# Define environment variable for MongoDB connection string
ENV MONGO_URI mongodb://localhost:27017

# Run log_service.py when the container launches
CMD ["python3", "log_service.py"]